// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckEmailExists(ctx context.Context, email string) (bool, error)
	CheckWalletExists(ctx context.Context, arg CheckWalletExistsParams) (bool, error)
	CountActiveEmployees(ctx context.Context, companyID uuid.UUID) (int64, error)
	CountActiveOTPsForUser(ctx context.Context, arg CountActiveOTPsForUserParams) (int64, error)
	CountCompanyEmployees(ctx context.Context, companyID uuid.UUID) (int64, error)
	// Counts the number of waitlist entries matching a search query
	CountSearchWaitlist(ctx context.Context, dollar_1 pgtype.Text) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountUsersByAccountType(ctx context.Context, accountType string) (int64, error)
	// Counts the total number of waitlist entries matching filters
	CountWaitlistEntries(ctx context.Context, arg CountWaitlistEntriesParams) (int64, error)
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Companies, error)
	CreateCompanyCountryKYBStatus(ctx context.Context, arg CreateCompanyCountryKYBStatusParams) (CompanyCountryKybStatus, error)
	// ================================
	// COMPANY_EMPLOYEES TABLE QUERIES
	// ================================
	CreateCompanyEmployee(ctx context.Context, arg CreateCompanyEmployeeParams) (CompanyEmployees, error)
	CreateCompanyFeatureFlag(ctx context.Context, arg CreateCompanyFeatureFlagParams) (CompanyFeatureFlags, error)
	CreateCompanySetting(ctx context.Context, arg CreateCompanySettingParams) (CompanySettings, error)
	// ================================
	// COMPANY_USERS TABLE QUERIES
	// ================================
	CreateCompanyUser(ctx context.Context, arg CreateCompanyUserParams) (CompanyUsers, error)
	CreateExchangeRate(ctx context.Context, arg CreateExchangeRateParams) (ExchangeRates, error)
	CreateFeatureFlag(ctx context.Context, arg CreateFeatureFlagParams) (FeatureFlags, error)
	CreateFiatTransaction(ctx context.Context, arg CreateFiatTransactionParams) (FiatTransactions, error)
	CreateKYBDocument(ctx context.Context, arg CreateKYBDocumentParams) (KybDocuments, error)
	CreateKYCDocument(ctx context.Context, arg CreateKYCDocumentParams) (KycDocuments, error)
	CreateOTPVerification(ctx context.Context, arg CreateOTPVerificationParams) (Otp, error)
	// ================================
	// PERSONAL_USERS TABLE QUERIES
	// ================================
	CreatePersonalUser(ctx context.Context, arg CreatePersonalUserParams) (PersonalUsers, error)
	CreateSecurityEvent(ctx context.Context, arg CreateSecurityEventParams) (SecurityEvents, error)
	// Add these exact queries to your auth.sql file to match your repository
	CreateSession(ctx context.Context, arg CreateSessionParams) (Sessions, error)
	CreateSupportedCountry(ctx context.Context, arg CreateSupportedCountryParams) (SupportedCountries, error)
	CreateSupportedNetwork(ctx context.Context, arg CreateSupportedNetworkParams) (SupportedNetworks, error)
	CreateSupportedToken(ctx context.Context, arg CreateSupportedTokenParams) (SupportedTokens, error)
	CreateSystemSetting(ctx context.Context, arg CreateSystemSettingParams) (SystemSettings, error)
	// ================================
	// USERS TABLE QUERIES
	// ================================
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	CreateUserCountryKYCStatus(ctx context.Context, arg CreateUserCountryKYCStatusParams) (UserCountryKycStatus, error)
	CreateUserDevice(ctx context.Context, arg CreateUserDeviceParams) (UserDevices, error)
	CreateUserFeatureFlag(ctx context.Context, arg CreateUserFeatureFlagParams) (UserFeatureFlags, error)
	CreateUserSetting(ctx context.Context, arg CreateUserSettingParams) (UserSettings, error)
	CreateUserWallet(ctx context.Context, arg CreateUserWalletParams) (UserWallets, error)
	// Creates a new waitlist entry and returns the created entry
	CreateWaitlistEntry(ctx context.Context, arg CreateWaitlistEntryParams) (Waitlist, error)
	CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) (WalletTransactions, error)
	DeactivateCompanyUser(ctx context.Context, id uuid.UUID) (CompanyUsers, error)
	DeleteCompany(ctx context.Context, id uuid.UUID) error
	DeleteCompanyEmployee(ctx context.Context, id uuid.UUID) error
	DeleteCompanySetting(ctx context.Context, arg DeleteCompanySettingParams) error
	DeleteCompanyUser(ctx context.Context, id uuid.UUID) error
	DeleteExpiredOTPs(ctx context.Context) error
	DeleteOTPByID(ctx context.Context, id uuid.UUID) error
	DeleteOTPByUserID(ctx context.Context, userID pgtype.UUID) error
	DeleteOTPByUserIDAndPurpose(ctx context.Context, arg DeleteOTPByUserIDAndPurposeParams) error
	DeletePersonalUser(ctx context.Context, id uuid.UUID) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteSystemSetting(ctx context.Context, settingKey string) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserSetting(ctx context.Context, arg DeleteUserSettingParams) error
	DeleteUserWallet(ctx context.Context, id uuid.UUID) error
	// Permanently deletes a waitlist entry
	DeleteWaitlistEntry(ctx context.Context, id uuid.UUID) error
	// Retrieves all waitlist entries for export
	ExportWaitlistEntries(ctx context.Context) ([]Waitlist, error)
	GetActiveEmployees(ctx context.Context, arg GetActiveEmployeesParams) ([]GetActiveEmployeesRow, error)
	GetActiveOTPsForUser(ctx context.Context, userID pgtype.UUID) ([]Otp, error)
	GetAllFeatureFlags(ctx context.Context) ([]FeatureFlags, error)
	GetAllLatestExchangeRates(ctx context.Context) ([]ExchangeRates, error)
	GetAllSystemSettings(ctx context.Context) ([]SystemSettings, error)
	GetCompaniesAccessibleToUser(ctx context.Context, userID uuid.UUID) ([]Companies, error)
	GetCompaniesByIndustry(ctx context.Context, arg GetCompaniesByIndustryParams) ([]Companies, error)
	GetCompaniesByKYBStatus(ctx context.Context, arg GetCompaniesByKYBStatusParams) ([]Companies, error)
	GetCompaniesByOwner(ctx context.Context, ownerID uuid.UUID) ([]Companies, error)
	GetCompanyAdministrators(ctx context.Context, companyID uuid.UUID) ([]GetCompanyAdministratorsRow, error)
	GetCompanyByID(ctx context.Context, id uuid.UUID) (Companies, error)
	GetCompanyByOwnerID(ctx context.Context, ownerID uuid.UUID) (Companies, error)
	GetCompanyEmployeeByEmployeeID(ctx context.Context, arg GetCompanyEmployeeByEmployeeIDParams) (CompanyEmployees, error)
	GetCompanyEmployeeByID(ctx context.Context, id uuid.UUID) (CompanyEmployees, error)
	GetCompanyEmployeeWithDetails(ctx context.Context, id uuid.UUID) (GetCompanyEmployeeWithDetailsRow, error)
	GetCompanyFeatureFlag(ctx context.Context, arg GetCompanyFeatureFlagParams) (CompanyFeatureFlags, error)
	GetCompanyFeatureFlags(ctx context.Context, companyID uuid.UUID) ([]GetCompanyFeatureFlagsRow, error)
	GetCompanyFiatTransactions(ctx context.Context, arg GetCompanyFiatTransactionsParams) ([]GetCompanyFiatTransactionsRow, error)
	GetCompanyKYBStatus(ctx context.Context, arg GetCompanyKYBStatusParams) (GetCompanyKYBStatusRow, error)
	GetCompanySetting(ctx context.Context, arg GetCompanySettingParams) (CompanySettings, error)
	GetCompanySettings(ctx context.Context, companyID uuid.UUID) ([]CompanySettings, error)
	GetCompanyTransactions(ctx context.Context, arg GetCompanyTransactionsParams) ([]GetCompanyTransactionsRow, error)
	GetCompanyUserByCompanyAndUser(ctx context.Context, arg GetCompanyUserByCompanyAndUserParams) (CompanyUsers, error)
	GetCompanyUserByID(ctx context.Context, id uuid.UUID) (CompanyUsers, error)
	GetCompanyUserWithDetails(ctx context.Context, id uuid.UUID) (GetCompanyUserWithDetailsRow, error)
	GetCompanyWithOwnerDetails(ctx context.Context, id uuid.UUID) (GetCompanyWithOwnerDetailsRow, error)
	GetDefaultWalletByUser(ctx context.Context, userID uuid.UUID) (UserWallets, error)
	GetEmployeesByDepartment(ctx context.Context, arg GetEmployeesByDepartmentParams) ([]GetEmployeesByDepartmentRow, error)
	GetEmployeesByManager(ctx context.Context, managerID pgtype.UUID) ([]GetEmployeesByManagerRow, error)
	GetExchangeRateHistory(ctx context.Context, arg GetExchangeRateHistoryParams) ([]ExchangeRates, error)
	GetFeatureFlag(ctx context.Context, flagKey string) (FeatureFlags, error)
	GetFiatTransactionByReference(ctx context.Context, transactionReference string) (GetFiatTransactionByReferenceRow, error)
	GetFiatTransactionsByBankAccount(ctx context.Context, arg GetFiatTransactionsByBankAccountParams) ([]GetFiatTransactionsByBankAccountRow, error)
	GetKYBCountryRequirements(ctx context.Context, countryID uuid.UUID) ([]KybCountryRequirements, error)
	GetKYBDocumentsByCompany(ctx context.Context, companyID uuid.UUID) ([]GetKYBDocumentsByCompanyRow, error)
	GetKYCCountryRequirements(ctx context.Context, countryID uuid.UUID) ([]KycCountryRequirements, error)
	GetKYCDocumentsByCountry(ctx context.Context, arg GetKYCDocumentsByCountryParams) ([]GetKYCDocumentsByCountryRow, error)
	GetKYCDocumentsByUser(ctx context.Context, userID uuid.UUID) ([]GetKYCDocumentsByUserRow, error)
	GetLatestExchangeRate(ctx context.Context, arg GetLatestExchangeRateParams) (ExchangeRates, error)
	GetMainnetNetworks(ctx context.Context) ([]SupportedNetworks, error)
	GetOTPVerificationByID(ctx context.Context, id uuid.UUID) (Otp, error)
	GetOTPVerificationByUserAndPurpose(ctx context.Context, arg GetOTPVerificationByUserAndPurposeParams) (Otp, error)
	GetPendingTransactions(ctx context.Context, userID uuid.UUID) ([]GetPendingTransactionsRow, error)
	GetPersonalUserByID(ctx context.Context, id uuid.UUID) (PersonalUsers, error)
	GetPersonalUserByUserID(ctx context.Context, userID uuid.UUID) (PersonalUsers, error)
	GetPersonalUserWithUserDetails(ctx context.Context, id uuid.UUID) (GetPersonalUserWithUserDetailsRow, error)
	GetPersonalUsersByKYCStatus(ctx context.Context, arg GetPersonalUsersByKYCStatusParams) ([]PersonalUsers, error)
	GetPublicSystemSettings(ctx context.Context) ([]GetPublicSystemSettingsRow, error)
	GetSecurityEventsByCompany(ctx context.Context, arg GetSecurityEventsByCompanyParams) ([]SecurityEvents, error)
	GetSecurityEventsByType(ctx context.Context, arg GetSecurityEventsByTypeParams) ([]SecurityEvents, error)
	GetSecurityEventsByUser(ctx context.Context, arg GetSecurityEventsByUserParams) ([]SecurityEvents, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (Sessions, error)
	GetSessionByRefreshToken(ctx context.Context, refreshToken pgtype.Text) (Sessions, error)
	GetSessionsByUser(ctx context.Context, userID uuid.UUID) ([]Sessions, error)
	GetStablecoinsByNetwork(ctx context.Context, chainID int32) ([]GetStablecoinsByNetworkRow, error)
	GetSupportedCountries(ctx context.Context) ([]SupportedCountries, error)
	GetSupportedCountryByCode(ctx context.Context, countryCode string) (SupportedCountries, error)
	GetSupportedNetworkByChainID(ctx context.Context, chainID int32) (SupportedNetworks, error)
	GetSupportedNetworks(ctx context.Context) ([]SupportedNetworks, error)
	GetSystemSetting(ctx context.Context, settingKey string) (SystemSettings, error)
	GetTestnetNetworks(ctx context.Context) ([]SupportedNetworks, error)
	GetTokenByContract(ctx context.Context, arg GetTokenByContractParams) (GetTokenByContractRow, error)
	GetTokensByNetwork(ctx context.Context, chainID int32) ([]GetTokensByNetworkRow, error)
	GetTransactionsByToken(ctx context.Context, arg GetTransactionsByTokenParams) ([]GetTransactionsByTokenRow, error)
	GetUnverifiedOTPsForUser(ctx context.Context, userID pgtype.UUID) ([]Otp, error)
	GetUser(ctx context.Context, id uuid.UUID) (Users, error)
	GetUserByEmail(ctx context.Context, email string) (Users, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (Users, error)
	GetUserCompanies(ctx context.Context, userID uuid.UUID) ([]GetUserCompaniesRow, error)
	GetUserDeviceByID(ctx context.Context, id uuid.UUID) (UserDevices, error)
	GetUserDeviceByToken(ctx context.Context, deviceToken pgtype.Text) (UserDevices, error)
	GetUserDevicesByUser(ctx context.Context, userID uuid.UUID) ([]UserDevices, error)
	GetUserFeatureFlag(ctx context.Context, arg GetUserFeatureFlagParams) (UserFeatureFlags, error)
	GetUserFeatureFlags(ctx context.Context, userID uuid.UUID) ([]GetUserFeatureFlagsRow, error)
	GetUserFiatTransactions(ctx context.Context, arg GetUserFiatTransactionsParams) ([]GetUserFiatTransactionsRow, error)
	GetUserKYCStatus(ctx context.Context, arg GetUserKYCStatusParams) (GetUserKYCStatusRow, error)
	GetUserKYCStatusByCountryCode(ctx context.Context, arg GetUserKYCStatusByCountryCodeParams) (GetUserKYCStatusByCountryCodeRow, error)
	GetUserSetting(ctx context.Context, arg GetUserSettingParams) (UserSettings, error)
	GetUserSettings(ctx context.Context, userID uuid.UUID) ([]UserSettings, error)
	GetUserTransactions(ctx context.Context, arg GetUserTransactionsParams) ([]GetUserTransactionsRow, error)
	GetUserWalletsByNetwork(ctx context.Context, arg GetUserWalletsByNetworkParams) ([]GetUserWalletsByNetworkRow, error)
	GetUserWalletsByUser(ctx context.Context, userID uuid.UUID) ([]GetUserWalletsByUserRow, error)
	GetUsersByAccountType(ctx context.Context, arg GetUsersByAccountTypeParams) ([]Users, error)
	// Retrieves a single waitlist entry by email address
	GetWaitlistEntryByEmail(ctx context.Context, email string) (Waitlist, error)
	// Retrieves a single waitlist entry by ID
	GetWaitlistEntryByID(ctx context.Context, id uuid.UUID) (Waitlist, error)
	// Retrieves a single waitlist entry by referral code
	GetWaitlistEntryByReferralCode(ctx context.Context, referralCode string) (Waitlist, error)
	// Gets the position of an entry in the waitlist (by signup date)
	GetWaitlistPosition(ctx context.Context, id uuid.UUID) (int64, error)
	// Gets waitlist statistics grouped by referral source
	GetWaitlistStatsBySource(ctx context.Context) ([]GetWaitlistStatsBySourceRow, error)
	// Gets waitlist statistics grouped by status
	GetWaitlistStatsByStatus(ctx context.Context) ([]GetWaitlistStatsByStatusRow, error)
	GetWalletByAddress(ctx context.Context, walletAddress string) (UserWallets, error)
	GetWalletByID(ctx context.Context, id uuid.UUID) (UserWallets, error)
	GetWalletTransactionByHash(ctx context.Context, transactionHash string) (GetWalletTransactionByHashRow, error)
	GetWalletTransactionsByAddress(ctx context.Context, arg GetWalletTransactionsByAddressParams) ([]GetWalletTransactionsByAddressRow, error)
	GetWalletTransactionsByNetwork(ctx context.Context, arg GetWalletTransactionsByNetworkParams) ([]GetWalletTransactionsByNetworkRow, error)
	GetWalletsByUserID(ctx context.Context, userID uuid.UUID) ([]UserWallets, error)
	InValidateOTP(ctx context.Context, id uuid.UUID) error
	ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]ListCompaniesRow, error)
	ListCompanyEmployees(ctx context.Context, arg ListCompanyEmployeesParams) ([]ListCompanyEmployeesRow, error)
	ListCompanyUsers(ctx context.Context, arg ListCompanyUsersParams) ([]ListCompanyUsersRow, error)
	ListPersonalUsers(ctx context.Context, arg ListPersonalUsersParams) ([]ListPersonalUsersRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]Users, error)
	// Lists waitlist entries with pagination and filtering support
	ListWaitlistEntries(ctx context.Context, arg ListWaitlistEntriesParams) ([]Waitlist, error)
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	RevokeUserDevice(ctx context.Context, id uuid.UUID) error
	SearchCompaniesByName(ctx context.Context, arg SearchCompaniesByNameParams) ([]Companies, error)
	SearchTokens(ctx context.Context, arg SearchTokensParams) ([]SearchTokensRow, error)
	SearchUsersByEmail(ctx context.Context, arg SearchUsersByEmailParams) ([]Users, error)
	// Searches for waitlist entries by email or name with pagination
	SearchWaitlist(ctx context.Context, arg SearchWaitlistParams) ([]Waitlist, error)
	SetUserWalletAsDefault(ctx context.Context, arg SetUserWalletAsDefaultParams) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Companies, error)
	UpdateCompanyEmployee(ctx context.Context, arg UpdateCompanyEmployeeParams) (CompanyEmployees, error)
	UpdateCompanyFeatureFlag(ctx context.Context, arg UpdateCompanyFeatureFlagParams) (CompanyFeatureFlags, error)
	UpdateCompanyKYB(ctx context.Context, arg UpdateCompanyKYBParams) (Companies, error)
	UpdateCompanyKYBStatus(ctx context.Context, arg UpdateCompanyKYBStatusParams) (CompanyCountryKybStatus, error)
	UpdateCompanySetting(ctx context.Context, arg UpdateCompanySettingParams) (CompanySettings, error)
	UpdateCompanyUser(ctx context.Context, arg UpdateCompanyUserParams) (CompanyUsers, error)
	UpdateEmployeeStatus(ctx context.Context, arg UpdateEmployeeStatusParams) (CompanyEmployees, error)
	UpdateFeatureFlag(ctx context.Context, arg UpdateFeatureFlagParams) (FeatureFlags, error)
	UpdateFiatTransaction(ctx context.Context, arg UpdateFiatTransactionParams) (FiatTransactions, error)
	UpdateKYCDocument(ctx context.Context, arg UpdateKYCDocumentParams) (KycDocuments, error)
	UpdateNetworkStatus(ctx context.Context, arg UpdateNetworkStatusParams) (SupportedNetworks, error)
	UpdateOTPAttempts(ctx context.Context, id uuid.UUID) (Otp, error)
	UpdatePersonalUser(ctx context.Context, arg UpdatePersonalUserParams) (PersonalUsers, error)
	UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) (Sessions, error)
	UpdateSessionLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateSystemSetting(ctx context.Context, arg UpdateSystemSettingParams) (SystemSettings, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (Users, error)
	UpdateUserAddress(ctx context.Context, id uuid.UUID) (Users, error)
	UpdateUserCompanyDetails(ctx context.Context, id uuid.UUID) (Users, error)
	UpdateUserDevice(ctx context.Context, arg UpdateUserDeviceParams) (UserDevices, error)
	UpdateUserFeatureFlag(ctx context.Context, arg UpdateUserFeatureFlagParams) (UserFeatureFlags, error)
	UpdateUserKYCStatus(ctx context.Context, arg UpdateUserKYCStatusParams) (UserCountryKycStatus, error)
	UpdateUserLoginTime(ctx context.Context, id uuid.UUID) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserPersonalDetails(ctx context.Context, arg UpdateUserPersonalDetailsParams) (Users, error)
	UpdateUserSetting(ctx context.Context, arg UpdateUserSettingParams) (UserSettings, error)
	UpdateUserWallet(ctx context.Context, arg UpdateUserWalletParams) (UserWallets, error)
	UpdateWalletTransaction(ctx context.Context, arg UpdateWalletTransactionParams) (WalletTransactions, error)
	VerifyEmail(ctx context.Context, id uuid.UUID) error
	VerifyOTP(ctx context.Context, arg VerifyOTPParams) (Otp, error)
	VerifyPhoneNumber(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
